---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: java-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: quay.io/strimzi-examples/java-kafka-consumer:latest
          env:
            - name: CA_CRT
              valueFrom:
                secretKeyRef:
                  name: carbon-dev-cluster-ca-cert
                  key: ca.crt
            - name: USER_CRT
              valueFrom:
                secretKeyRef:
                  name: probe-user
                  key: user.crt
            - name: USER_KEY
              valueFrom:
                secretKeyRef:
                  name: probe-user
                  key: user.key
            - name: BOOTSTRAP_SERVERS
              value: [BROKER ENDPOINT]
            - name: TOPIC
              value: my-topic
            - name: GROUP_ID
              value: probe-group
            - name: LOG_LEVEL
              value: "INFO"
          resources:
            limits:
              cpu: 140m
              memory: 150Mi
            requests:
              cpu: 180m
              memory: 110Mi
