---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-producer
  name: java-kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: quay.io/strimzi-examples/java-kafka-producer:latest
          env:
            - name: CA_CRT
              valueFrom:
                secretKeyRef:
                  name: carbon-dev-cluster-ca-cert
                  key: ca.crt
            - name: USER_CRT
              valueFrom:
                secretKeyRef:
                  name: my-user
                  key: user.crt
            - name: USER_KEY
              valueFrom:
                secretKeyRef:
                  name: my-user
                  key: user.key
            - name: BOOTSTRAP_SERVERS
              value: [BROKER ENDPOINT]
            - name: TOPIC
              value: my-topic
            - name: DELAY_MS
              value: "300000"
            - name: LOG_LEVEL
              value: "INFO"
            - name: MESSAGE_COUNT
              value: "1000"
          resources:
            limits:
              cpu: 140m
              memory: 150Mi
            requests:
              cpu: 180m
              memory: 110Mi
